// Inserir novo colaborador (Tag 1)

INSERT INTO brh.colaborador (matricula, nome, cpf, salario, departamento, cep, logradouro, complemento_endereco) 
    VALUES ('B122', 'Fulano de Tal', '550.847.018-24', '28664', 'SEDES', '71111-100', 'Avenida das Castanheiras', 'Casa 5');
INSERT INTO brh.email_colaborador (colaborador, email, tipo) 
    VALUES ('B122', 'fulano.tal@brh.com;', 'T');
INSERT INTO brh.email_colaborador (colaborador, email, tipo) 
    VALUES ('B122', 'fulano@email.com;', 'P');
INSERT INTO brh.telefone_colaborador (colaborador, numero, tipo) 
    VALUES ('B122', '(61) 9 9999-9999', 'M'); 
INSERT INTO brh.telefone_colaborador (colaborador, numero, tipo) 
    VALUES ('B122', '(61) 3030-4040;', 'R');
INSERT INTO brh.dependente (cpf, colaborador, nome, parentesco, data_nascimento) 
    VALUES ('829.553.008-96', 'B122', 'Beltrana de Tal', 'CÃ´njuge', to_date('1995-06-02', 'yyyy-mm-dd'));
INSERT INTO brh.dependente (cpf, colaborador, nome, parentesco, data_nascimento) 
    VALUES ('061.299.588-70', 'B122', 'Cicrana de Tal', 'Filho(a)', to_date('2017-05-29', 'yyyy-mm-dd'));
INSERT INTO brh.atribuicao (projeto, colaborador, papel) 
    VALUES (2, 'B122', 1);

// Relatorio conjugues (Tag 2)

SELECT * FROM BRH.DEPENDENTE WHERE PARENTESCO = 'CÃ´njuge';

// Filtrar dependentes (Tag 3)

SELECT * FROM BRH.DEPENDENTE WHERE TO_CHAR(DATA_NASCIMENTO, 'MM') >= 4 AND TO_CHAR(DATA_NASCIMENTO, 'MM')<= 6; 

SELECT * FROM BRH.DEPENDENTE WHERE NOME LIKE 'H%';


// Lista maior salario (Tag 4)


SELECT BRH.COLABORADOR.NOME, MAX(BRH.COLABORADOR.SALARIO) AS MAIOR_SALARIO FROM BRH.COLABORADOR GROUP BY BRH.COLABORADOR.NOME ORDER BY MAIOR_SALARIO DESC;

// LISTA DE SENIORIDADE (Tag 5)

ALTER TABLE BRH.SENIORIDADE MODIFY (salario NVARCHAR2(50));

INSERT INTO BRH.SENIORIDADE (SENIORIDADE, SALARIO)
    VALUES ('JUNIOR', 'ATÉ 3000');
    
INSERT INTO BRH.SENIORIDADE (SENIORIDADE, SALARIO)
    VALUES ('PLENO', 'DE 3.001 ATÉ 6.000');
    
 INSERT INTO BRH.SENIORIDADE (SENIORIDADE, SALARIO)
    VALUES ('SENIOR', 'DE 6.001 ATÉ 20.000');

INSERT INTO BRH.SENIORIDADE (SENIORIDADE, SALARIO)
    VALUES ('CORPO DIRETOR', 'ACIMA DE 20.000');

UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'A123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'B123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'C123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'D123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'E123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'F123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'G123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'H123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'I123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'J123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'K123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'L123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'M123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'N123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'O123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'P123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'Q123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'R123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'JUNIOR' WHERE MATRICULA = 'S123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'T123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'U123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'V123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'W123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'SENIOR' WHERE MATRICULA = 'X123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'PLENO' WHERE MATRICULA = 'Y123';
UPDATE BRH.COLABORADOR SET SENIORIDADE = 'CORPO DIRETOR' WHERE MATRICULA = 'Z123';

SELECT MATRICULA, NOME, SALARIO, SENIORIDADE FROM BRH.COLABORADOR;


// Relatorio de contatos 

SELECT 
    BRH.COLABORADOR.NOME, 
    BRH.TELEFONE_COLABORADOR.NUMERO, 
    BRH.EMAIL_COLABORADOR.EMAIL 
FROM 
    BRH.TELEFONE_COLABORADOR 
        JOIN BRH.COLABORADOR ON BRH.TELEFONE_COLABORADOR.COLABORADOR = BRH.COLABORADOR.MATRICULA
        JOIN BRH.EMAIL_COLABORADOR ON BRH.EMAIL_COLABORADOR.COLABORADOR = BRH.COLABORADOR.MATRICULA 
WHERE
        brh.email_colaborador.tipo = 'T'
    AND brh.telefone_colaborador.tipo = 'M' OR brh.telefone_colaborador.tipo = 'C'
ORDER BY 
( brh.colaborador.nome );



